version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: cashkaro-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: cashkaro
    volumes:
      - mongodb_data:/data/db
      - ./infra/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - cashkaro-network

  redis:
    image: redis:7.2-alpine
    container_name: cashkaro-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - cashkaro-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cashkaro-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MONGO_URI=mongodb://admin:password123@mongodb:27017/cashkaro?authSource=admin
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - FRONTEND_URL=http://localhost:3000
    depends_on:
      - mongodb
      - redis
    volumes:
      - ./backend/uploads:/app/uploads
    networks:
      - cashkaro-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cashkaro-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:4000
    depends_on:
      - backend
    networks:
      - cashkaro-network

  nginx:
    image: nginx:alpine
    container_name: cashkaro-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./infra/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - cashkaro-network

volumes:
  mongodb_data:
  redis_data:

networks:
  cashkaro-network:
    driver: bridge