version: "3.9"
services:
  postgres:
    image: postgres:15
    container_name: ck_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ck
      POSTGRES_PASSWORD: ck
      POSTGRES_DB: cashkaro
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: ck_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
